In [55]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

In [56]:
wd_df = pd.read_csv('Weather_Data.csv')
wd_df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]

In [57]:
wd_df.shape

(3271, 22)

In [58]:
df_sydney_processed = pd.get_dummies(data=wd_df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])

In [59]:
df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)

In [60]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [61]:
df_sydney_processed = df_sydney_processed.astype(float)
x = df_sydney_processed
x.head()

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0     19.5     22.4      15.6          6.2       0.0           41.0   
1     19.5     25.6       6.0          3.4       2.7           41.0   
2     21.6     24.5       6.6          2.4       0.1           41.0   
3     20.2     22.8      18.8          2.2       0.0           41.0   
4     19.7     25.7      77.4          4.8       0.0           41.0   

   WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  ...  WindDir3pm_NNW  \
0          17.0          20.0         92.0         84.0  ...             0.0   
1           9.0          13.0         83.0         73.0  ...             0.0   
2          17.0           2.0         88.0         86.0  ...             0.0   
3          22.0          20.0         83.0         90.0  ...             0.0   
4          11.0           6.0         88.0         74.0  ...             0.0   

   WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  WindDir3pm_SSE  WindDir3pm_SSW  \
0            0.0           0.0            0.0             0.0             1.0   
1            0.0           0.0            0.0             0.0             0.0   
2            0.0           0.0            0.0             0.0             0.0   
3            0.0           0.0            0.0             0.0             0.0   
4            0.0           0.0            0.0             0.0             0.0   

   WindDir3pm_SW  WindDir3pm_W  WindDir3pm_WNW  WindDir3pm_WSW  
0            0.0           0.0             0.0             0.0  
1            0.0           0.0             0.0             0.0  
2            0.0           0.0             0.0             0.0  
3            0.0           0.0             0.0             0.0  
4            0.0           1.0             0.0             0.0  

[5 rows x 67 columns]

In [62]:
features = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
y = df_sydney_processed['RainTomorrow']

In [63]:
from sklearn.model_selection import train_test_split

In [64]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=10, shuffle=True)

## Linear Regression Model

In [65]:
regr.fit(x_train, y_train)

LinearRegression()

In [67]:
predictions_lr = regr.predict(x_test)
predictions_lr

array([ 1.68724897e-15,  1.02869102e-15,  1.00000000e+00,  1.00000000e+00,
        1.26950588e-15,  1.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        1.00000000e+00, -1.15926962e-15, -1.62557142e-15,  1.00000000e+00,
       -1.04747482e-15,  1.49141496e-15, -1.90413007e-16,  1.00000000e+00,
       -5.17381277e-16, -2.78558643e-16, -2.00269760e-15,  8.37776571e-16,
        5.68081281e-16,  1.00000000e+00, -1.45533813e-15, -1.16707588e-15,
        2.14086561e-15, -5.90131242e-16,  1.00000000e+00, -1.61521729e-15,
        1.00000000e+00,  2.68960743e-15,  1.00000000e+00, -1.90143311e-15,
       -4.81927866e-17, -2.31245416e-15,  9.01581869e-16,  1.00000000e+00,
       -6.00878397e-16,  1.00000000e+00, -2.85904113e-16,  7.41133500e-16,
       -2.07834780e-15,  1.00000000e+00,  1.00000000e+00, -1.88027762e-16,
       -1.07058188e-15,  1.00000000e+00,  5.85523383e-16,  2.87720152e-16,
        1.00000000e+00,  1.00000000e+00,  1.60581184e-15, -9.07938004e-16,
        2.25832536e-15, -

In [68]:
regr.score(x_test, y_test)

1.0

In [69]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculating MAE
LinearRegression_MAE = mean_absolute_error(y_test, predictions)

# Calculating MSE
LinearRegression_MSE = mean_squared_error(y_test, predictions)

# Calculating R²
LinearRegression_R2 = r2_score(y_test, predictions)

In [70]:
# Creating a DataFrame with the metrics
metrics_df = pd.DataFrame({
    'Metric': ['MAE', 'MSE', 'R²'],
    'Value': [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]
})

print(metrics_df)

  Metric         Value
0    MAE  1.004139e-15
1    MSE  1.629550e-30
2     R²  1.000000e+00


## KNN

In [72]:
from sklearn.neighbors import KNeighborsClassifier

# Creating the KNN model with n_neighbors set to 4
KNN = KNeighborsClassifier(n_neighbors=4)

# Training the KNN model using the training data
KNN.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [73]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
predictions_knn = KNN.predict(x_test)
predictions_knn

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0.

In [74]:
KNN.score(x_test, y_test)

0.8213740458015267

In [76]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score

# Calculating Accuracy Score
KNN_Accuracy_Score = accuracy_score(y_test, predictions_knn)

# Calculating Jaccard Index (Jaccard Score)
KNN_JaccardIndex = jaccard_score(y_test, predictions_knn, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

# Calculating F1 Score
KNN_F1_Score = f1_score(y_test, predictions_knn, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

print(f"KNN Accuracy Score: {KNN_Accuracy_Score}")
print(f"KNN Jaccard Index: {KNN_JaccardIndex}")
print(f"KNN F1 Score: {KNN_F1_Score}")


KNN Accuracy Score: 0.8213740458015267
KNN Jaccard Index: 0.43478260869565216
KNN F1 Score: 0.6060606060606061


## Decision Trees

In [77]:
from sklearn.tree import DecisionTreeClassifier
import sklearn.tree as tree

In [78]:
weather_tree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
weather_tree # it shows the default parameters

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [79]:
weather_tree.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [80]:
predTree = weather_tree.predict(x_test)
predTree

array([0., 0., 1., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 1., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0.

In [82]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score

# Calculating Accuracy Score
Tree_Accuracy_Score = accuracy_score(y_test, predTree)

# Calculating Jaccard Index (Jaccard Score)
Tree_JaccardIndex = jaccard_score(y_test, predTree, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

# Calculating F1 Score
Tree_F1_Score = f1_score(y_test, predTree, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

print(f"Tree Accuracy Score: {Tree_Accuracy_Score}")
print(f"Tree Jaccard Index: {Tree_JaccardIndex}")
print(f"Tree F1 Score: {Tree_F1_Score}")

Tree Accuracy Score: 1.0
Tree Jaccard Index: 1.0
Tree F1 Score: 1.0


## Logistic Regression

In [83]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1, shuffle=True)

In [84]:
from sklearn.linear_model import LogisticRegression

LR = LogisticRegression(solver='liblinear')

LR.fit(x_train, y_train)

LogisticRegression(solver='liblinear')

In [85]:
predictions_LR = LR.predict(x_test)

predict_proba = LR.predict_proba(x_test)

In [87]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score, log_loss

# Calculating Accuracy Score
LR_Accuracy_Score = accuracy_score(y_test, predictions_LR)

# Calculating Jaccard Index (Jaccard Score)
LR_JaccardIndex = jaccard_score(y_test, predictions_LR, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

# Calculating F1 Score
LR_F1_Score = f1_score(y_test, predictions_LR, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

# Calculating Log Loss
LR_Log_Loss = log_loss(y_test, predict_proba)

print(f"LR Accuracy Score: {LR_Accuracy_Score}")
print(f"LR Jaccard Index: {LR_JaccardIndex}")
print(f"LR F1 Score: {LR_F1_Score}")
print(f"LR Log Loss: {LR_Log_Loss}")

LR Accuracy Score: 1.0
LR Jaccard Index: 1.0
LR F1 Score: 1.0
LR Log Loss: 0.008365020541742313


## SVM

In [88]:
from sklearn.svm import SVC

SVM = SVC()

SVM.fit(x_train, y_train)

SVC()

In [90]:
predictions_SVM = SVM.predict(x_test)
predictions_SVM

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [91]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score

# Calculating Accuracy Score
SVM_Accuracy_Score = accuracy_score(y_test, predictions)

# Calculating Jaccard Index (Jaccard Score)
SVM_JaccardIndex = jaccard_score(y_test, predictions, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

# Calculating F1 Score
SVM_F1_Score = f1_score(y_test, predictions, average='binary')  # Use 'micro', 'macro', or 'weighted' for multi-class

print(f"SVM Accuracy Score: {SVM_Accuracy_Score}")
print(f"SVM Jaccard Index: {SVM_JaccardIndex}")
print(f"SVM F1 Score: {SVM_F1_Score}")

SVM Accuracy Score: 0.7221374045801526
SVM Jaccard Index: 0.0
SVM F1 Score: 0.0


In [93]:
import pandas as pd
from sklearn.metrics import accuracy_score, jaccard_score, f1_score, log_loss

# Calculating metrics for Logistic Regression
LR_Accuracy_Score = accuracy_score(y_test, predictions_LR)
LR_JaccardIndex = jaccard_score(y_test, predictions_LR, average='binary')
LR_F1_Score = f1_score(y_test, predictions_LR, average='binary')
LR_Log_Loss = log_loss(y_test, predict_proba)

# Calculating metrics for KNN
KNN_Accuracy_Score = accuracy_score(y_test, predictions_knn)
KNN_JaccardIndex = jaccard_score(y_test, predictions_knn, average='binary')
KNN_F1_Score = f1_score(y_test, predictions_knn, average='binary')
# KNN does not provide probability estimates directly, so Log Loss might not be applicable

# Calculating metrics for SVM
SVM_Accuracy_Score = accuracy_score(y_test, predictions_SVM)
SVM_JaccardIndex = jaccard_score(y_test, predictions_SVM, average='binary')
SVM_F1_Score = f1_score(y_test, predictions_SVM, average='binary')

# Creating a DataFrame with the metrics
metrics_df = pd.DataFrame({
    'Model': ['Logistic Regression', 'KNN', 'SVM'],
    'Accuracy': [LR_Accuracy_Score, KNN_Accuracy_Score, SVM_Accuracy_Score],
    'Jaccard Index': [LR_JaccardIndex, KNN_JaccardIndex, SVM_JaccardIndex],
    'F1 Score': [LR_F1_Score, KNN_F1_Score, SVM_F1_Score],
    'Log Loss': [LR_Log_Loss, None, None]  # Log Loss might not be applicable for KNN and SVM
})

print(metrics_df)

                 Model  Accuracy  Jaccard Index  F1 Score  Log Loss
0  Logistic Regression  1.000000       1.000000   1.00000  0.008365
1                  KNN  0.638168       0.109023   0.19661       NaN
2                  SVM  0.722137       0.000000   0.00000       NaN
